//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logicalFaultCause.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="logicalFaultCause">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="CHARGE_EXCEEDS_LIMIT"/>
 *     &lt;enumeration value="INSUFFICIENT_FUNDS"/>
 *     &lt;enumeration value="INVALID_CURRENCY"/>
 *     &lt;enumeration value="ACCOUNT_SUSPENDED"/>
 *     &lt;enumeration value="NOT_ELIGIBLE"/>
 *     &lt;enumeration value="SUBSCRIBER_NOT_FOUND"/>
 *     &lt;enumeration value="CHARGE_TOO_OLD"/>
 *     &lt;enumeration value="SUBSCRIPTION_CANCELLED"/>
 *     &lt;enumeration value="REFUND_EXCEEDS_CHARGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "logicalFaultCause")
@XmlEnum
public enum LogicalFaultCause {


    /**
     * The total charge for the specific subscriber has exceeds his limit.
     *                     
     * 
     */
    CHARGE_EXCEEDS_LIMIT,

    /**
     * Subscriber doesn’t have sufficient funds for this payment.
     * 
     */
    INSUFFICIENT_FUNDS,

    /**
     * Requested currency cannot be handled by the OpCo.
     * 
     */
    INVALID_CURRENCY,

    /**
     * Subscriber account is suspended.
     * 
     */
    ACCOUNT_SUSPENDED,

    /**
     * Direct carrier billing service is no longer provisioned for the subscriber.
     *                     
     * 
     */
    NOT_ELIGIBLE,

    /**
     * Subscriber cannot be found using identifier provided.
     * 
     */
    SUBSCRIBER_NOT_FOUND,

    /**
     * Refund is impossible because the charge was too long ago.
     * 
     */
    CHARGE_TOO_OLD,

    /**
     * The subscription ID supplied in the request was cancelled by the subscriber or by
     *                         the OpCo (Google specific).
     *                     
     * 
     */
    SUBSCRIPTION_CANCELLED,

    /**
     * Sum of all partial refunds for particular transaction exceeds its original amount.
     *                     
     * 
     */
    REFUND_EXCEEDS_CHARGE;

    public String value() {
        return name();
    }

    public static LogicalFaultCause fromValue(String v) {
        return valueOf(v);
    }

}
