//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for misbehaviorFaultCause.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="misbehaviorFaultCause">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="INVALID_CORRELATION_ID"/>
 *     &lt;enumeration value="INVALID_DATA"/>
 *     &lt;enumeration value="ALREADY_CHARGED"/>
 *     &lt;enumeration value="ALREADY_RELEASED"/>
 *     &lt;enumeration value="NOT_CHARGED"/>
 *     &lt;enumeration value="NOT_SUPPORTED"/>
 *     &lt;enumeration value="NOT_RESERVED"/>
 *     &lt;enumeration value="OUT_OF_ORDER"/>
 *     &lt;enumeration value="INVALID_SENDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "misbehaviorFaultCause")
@XmlEnum
public enum MisbehaviorFaultCause {


    /**
     * Related request with specified CorrelationID was not found or appears to be of
     *                         unexpected type.
     *                     
     * 
     */
    INVALID_CORRELATION_ID,

    /**
     * Message has been successfully transmitted, but it’s data is invalid.
     *                     
     * 
     */
    INVALID_DATA,

    /**
     * Subscriber account has already been charged.
     * 
     */
    ALREADY_CHARGED,

    /**
     * Funds reserved for this transaction has been already released.
     *                     
     * 
     */
    ALREADY_RELEASED,

    /**
     * Subscriber account has not been charged yet.
     * 
     */
    NOT_CHARGED,

    /**
     * Requested operation is not supported for particular Partner.
     * 
     */
    NOT_SUPPORTED,

    /**
     * There was no successful funds reservation for this transaction.
     * 
     */
    NOT_RESERVED,

    /**
     * Message has been successfully transmitted but it violates the charging state machine.
     * 
     */
    OUT_OF_ORDER,

    /**
     * Requested SenderMSISDN or SenderName is not allowed to be used by particular Partner.
     * 
     */
    INVALID_SENDER;

    public String value() {
        return name();
    }

    public static MisbehaviorFaultCause fromValue(String v) {
        return valueOf(v);
    }

}
