//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arcanainfo.esb.mediators.ott.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IMSI_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "IMSI");
    private final static QName _RequestRefundSubscriberMessageResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RequestRefundSubscriberMessageResponse");
    private final static QName _GetSubscriberImsiResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "GetSubscriberImsiResponse");
    private final static QName _ReleaseFundsMessage_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReleaseFundsMessage");
    private final static QName _MisbehaviorFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "MisbehaviorFault");
    private final static QName _ReleaseFundsCallbackResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReleaseFundsCallbackResponse");
    private final static QName _LogicalFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "LogicalFault");
    private final static QName _CheckMsisdnResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "CheckMsisdnResponse");
    private final static QName _GenericFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "GenericFault");
    private final static QName _SystemFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "SystemFault");
    private final static QName _ChargeSubscriberCallback_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberCallback");
    private final static QName _ChargeSubscriberCallbackResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberCallbackResponse");
    private final static QName _ServiceFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ServiceFault");
    private final static QName _GetSubscriberInfoRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "GetSubscriberInfoRequest");
    private final static QName _ConveyResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ConveyResponse");
    private final static QName _RequestRefundSubscriberCallback_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RequestRefundSubscriberCallback");
    private final static QName _PartnerId_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "PartnerId");
    private final static QName _GetSubscriberImsiRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "GetSubscriberImsiRequest");
    private final static QName _ChargeSubscriberImmediatelyRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberImmediatelyRequest");
    private final static QName _GetSubscriberInfoResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "GetSubscriberInfoResponse");
    private final static QName _SendSMSRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "SendSMSRequest");
    private final static QName _ConveySMSResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ConveySMSResponse");
    private final static QName _ReserveFundsResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReserveFundsResponse");
    private final static QName _ReleaseFundsCallback_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReleaseFundsCallback");
    private final static QName _ConveySMSRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ConveySMSRequest");
    private final static QName _ConveyRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ConveyRequest");
    private final static QName _CheckMsisdnRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "CheckMsisdnRequest");
    private final static QName _RefundSubscriberCallback_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RefundSubscriberCallback");
    private final static QName _ReleaseFundsMessageResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReleaseFundsMessageResponse");
    private final static QName _RefundSubscriberMessageResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RefundSubscriberMessageResponse");
    private final static QName _RequestRefundSubscriberMessage_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RequestRefundSubscriberMessage");
    private final static QName _ChargeSubscriberMessageResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberMessageResponse");
    private final static QName _RefundSubscriberMessage_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RefundSubscriberMessage");
    private final static QName _ChargeSubscriberImmediatelyResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberImmediatelyResponse");
    private final static QName _ReserveFundsRequest_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ReserveFundsRequest");
    private final static QName _RefundSubscriberCallbackResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RefundSubscriberCallbackResponse");
    private final static QName _SendSMSResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "SendSMSResponse");
    private final static QName _ChargeSubscriberMessage_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "ChargeSubscriberMessage");
    private final static QName _RequestRefundSubscriberCallbackResponse_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "RequestRefundSubscriberCallbackResponse");
    private final static QName _PolicyFault_QNAME = new QName("urn:vimpelcom:carrier-billing-hub:types", "PolicyFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arcanainfo.esb.mediators.ott.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConveySMSRequest }
     * 
     */
    public ConveySMSRequest createConveySMSRequest() {
        return new ConveySMSRequest();
    }

    /**
     * Create an instance of {@link ConveyRequest }
     * 
     */
    public ConveyRequest createConveyRequest() {
        return new ConveyRequest();
    }

    /**
     * Create an instance of {@link CheckMsisdnRequest }
     * 
     */
    public CheckMsisdnRequest createCheckMsisdnRequest() {
        return new CheckMsisdnRequest();
    }

    /**
     * Create an instance of {@link RefundSubscriberCallback }
     * 
     */
    public RefundSubscriberCallback createRefundSubscriberCallback() {
        return new RefundSubscriberCallback();
    }

    /**
     * Create an instance of {@link ReleaseFundsMessageResponse }
     * 
     */
    public ReleaseFundsMessageResponse createReleaseFundsMessageResponse() {
        return new ReleaseFundsMessageResponse();
    }

    /**
     * Create an instance of {@link RequestRefundSubscriberCallback }
     * 
     */
    public RequestRefundSubscriberCallback createRequestRefundSubscriberCallback() {
        return new RequestRefundSubscriberCallback();
    }

    /**
     * Create an instance of {@link GetSubscriberImsiRequest }
     * 
     */
    public GetSubscriberImsiRequest createGetSubscriberImsiRequest() {
        return new GetSubscriberImsiRequest();
    }

    /**
     * Create an instance of {@link ChargeSubscriberImmediatelyRequest }
     * 
     */
    public ChargeSubscriberImmediatelyRequest createChargeSubscriberImmediatelyRequest() {
        return new ChargeSubscriberImmediatelyRequest();
    }

    /**
     * Create an instance of {@link GetSubscriberInfoResponse }
     * 
     */
    public GetSubscriberInfoResponse createGetSubscriberInfoResponse() {
        return new GetSubscriberInfoResponse();
    }

    /**
     * Create an instance of {@link SendSMSRequest }
     * 
     */
    public SendSMSRequest createSendSMSRequest() {
        return new SendSMSRequest();
    }

    /**
     * Create an instance of {@link ReserveFundsResponse }
     * 
     */
    public ReserveFundsResponse createReserveFundsResponse() {
        return new ReserveFundsResponse();
    }

    /**
     * Create an instance of {@link ReleaseFundsCallback }
     * 
     */
    public ReleaseFundsCallback createReleaseFundsCallback() {
        return new ReleaseFundsCallback();
    }

    /**
     * Create an instance of {@link ReleaseFundsCallbackResponse }
     * 
     */
    public ReleaseFundsCallbackResponse createReleaseFundsCallbackResponse() {
        return new ReleaseFundsCallbackResponse();
    }

    /**
     * Create an instance of {@link LogicalFault }
     * 
     */
    public LogicalFault createLogicalFault() {
        return new LogicalFault();
    }

    /**
     * Create an instance of {@link CheckMsisdnResponse }
     * 
     */
    public CheckMsisdnResponse createCheckMsisdnResponse() {
        return new CheckMsisdnResponse();
    }

    /**
     * Create an instance of {@link SystemFault }
     * 
     */
    public SystemFault createSystemFault() {
        return new SystemFault();
    }

    /**
     * Create an instance of {@link ChargeSubscriberCallback }
     * 
     */
    public ChargeSubscriberCallback createChargeSubscriberCallback() {
        return new ChargeSubscriberCallback();
    }

    /**
     * Create an instance of {@link ChargeSubscriberCallbackResponse }
     * 
     */
    public ChargeSubscriberCallbackResponse createChargeSubscriberCallbackResponse() {
        return new ChargeSubscriberCallbackResponse();
    }

    /**
     * Create an instance of {@link ServiceFault }
     * 
     */
    public ServiceFault createServiceFault() {
        return new ServiceFault();
    }

    /**
     * Create an instance of {@link GetSubscriberInfoRequest }
     * 
     */
    public GetSubscriberInfoRequest createGetSubscriberInfoRequest() {
        return new GetSubscriberInfoRequest();
    }

    /**
     * Create an instance of {@link RequestRefundSubscriberMessageResponse }
     * 
     */
    public RequestRefundSubscriberMessageResponse createRequestRefundSubscriberMessageResponse() {
        return new RequestRefundSubscriberMessageResponse();
    }

    /**
     * Create an instance of {@link GetSubscriberImsiResponse }
     * 
     */
    public GetSubscriberImsiResponse createGetSubscriberImsiResponse() {
        return new GetSubscriberImsiResponse();
    }

    /**
     * Create an instance of {@link ReleaseFundsMessage }
     * 
     */
    public ReleaseFundsMessage createReleaseFundsMessage() {
        return new ReleaseFundsMessage();
    }

    /**
     * Create an instance of {@link MisbehaviorFault }
     * 
     */
    public MisbehaviorFault createMisbehaviorFault() {
        return new MisbehaviorFault();
    }

    /**
     * Create an instance of {@link RefundSubscriberCallbackResponse }
     * 
     */
    public RefundSubscriberCallbackResponse createRefundSubscriberCallbackResponse() {
        return new RefundSubscriberCallbackResponse();
    }

    /**
     * Create an instance of {@link SendSMSResponse }
     * 
     */
    public SendSMSResponse createSendSMSResponse() {
        return new SendSMSResponse();
    }

    /**
     * Create an instance of {@link ChargeSubscriberMessage }
     * 
     */
    public ChargeSubscriberMessage createChargeSubscriberMessage() {
        return new ChargeSubscriberMessage();
    }

    /**
     * Create an instance of {@link RequestRefundSubscriberCallbackResponse }
     * 
     */
    public RequestRefundSubscriberCallbackResponse createRequestRefundSubscriberCallbackResponse() {
        return new RequestRefundSubscriberCallbackResponse();
    }

    /**
     * Create an instance of {@link PolicyFault }
     * 
     */
    public PolicyFault createPolicyFault() {
        return new PolicyFault();
    }

    /**
     * Create an instance of {@link ReserveFundsRequest }
     * 
     */
    public ReserveFundsRequest createReserveFundsRequest() {
        return new ReserveFundsRequest();
    }

    /**
     * Create an instance of {@link ChargeSubscriberImmediatelyResponse }
     * 
     */
    public ChargeSubscriberImmediatelyResponse createChargeSubscriberImmediatelyResponse() {
        return new ChargeSubscriberImmediatelyResponse();
    }

    /**
     * Create an instance of {@link RefundSubscriberMessageResponse }
     * 
     */
    public RefundSubscriberMessageResponse createRefundSubscriberMessageResponse() {
        return new RefundSubscriberMessageResponse();
    }

    /**
     * Create an instance of {@link RequestRefundSubscriberMessage }
     * 
     */
    public RequestRefundSubscriberMessage createRequestRefundSubscriberMessage() {
        return new RequestRefundSubscriberMessage();
    }

    /**
     * Create an instance of {@link ChargeSubscriberMessageResponse }
     * 
     */
    public ChargeSubscriberMessageResponse createChargeSubscriberMessageResponse() {
        return new ChargeSubscriberMessageResponse();
    }

    /**
     * Create an instance of {@link RefundSubscriberMessage }
     * 
     */
    public RefundSubscriberMessage createRefundSubscriberMessage() {
        return new RefundSubscriberMessage();
    }

    /**
     * Create an instance of {@link BillingOperationMessageResponse }
     * 
     */
    public BillingOperationMessageResponse createBillingOperationMessageResponse() {
        return new BillingOperationMessageResponse();
    }

    /**
     * Create an instance of {@link BillingOperationCallback }
     * 
     */
    public BillingOperationCallback createBillingOperationCallback() {
        return new BillingOperationCallback();
    }

    /**
     * Create an instance of {@link RefundSubscriberByOpCoRequest }
     * 
     */
    public RefundSubscriberByOpCoRequest createRefundSubscriberByOpCoRequest() {
        return new RefundSubscriberByOpCoRequest();
    }

    /**
     * Create an instance of {@link OpcoInteractionFault }
     * 
     */
    public OpcoInteractionFault createOpcoInteractionFault() {
        return new OpcoInteractionFault();
    }

    /**
     * Create an instance of {@link BillingOperationMessage }
     * 
     */
    public BillingOperationMessage createBillingOperationMessage() {
        return new BillingOperationMessage();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link SMSMessageObject }
     * 
     */
    public SMSMessageObject createSMSMessageObject() {
        return new SMSMessageObject();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link RequestedSubscriberAttributes }
     * 
     */
    public RequestedSubscriberAttributes createRequestedSubscriberAttributes() {
        return new RequestedSubscriberAttributes();
    }

    /**
     * Create an instance of {@link BillingOperationCallbackResponse }
     * 
     */
    public BillingOperationCallbackResponse createBillingOperationCallbackResponse() {
        return new BillingOperationCallbackResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "IMSI")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIMSI(String value) {
        return new JAXBElement<String>(_IMSI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestRefundSubscriberMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RequestRefundSubscriberMessageResponse")
    public JAXBElement<RequestRefundSubscriberMessageResponse> createRequestRefundSubscriberMessageResponse(RequestRefundSubscriberMessageResponse value) {
        return new JAXBElement<RequestRefundSubscriberMessageResponse>(_RequestRefundSubscriberMessageResponse_QNAME, RequestRefundSubscriberMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSubscriberImsiResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "GetSubscriberImsiResponse")
    public JAXBElement<GetSubscriberImsiResponse> createGetSubscriberImsiResponse(GetSubscriberImsiResponse value) {
        return new JAXBElement<GetSubscriberImsiResponse>(_GetSubscriberImsiResponse_QNAME, GetSubscriberImsiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseFundsMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReleaseFundsMessage")
    public JAXBElement<ReleaseFundsMessage> createReleaseFundsMessage(ReleaseFundsMessage value) {
        return new JAXBElement<ReleaseFundsMessage>(_ReleaseFundsMessage_QNAME, ReleaseFundsMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MisbehaviorFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "MisbehaviorFault")
    public JAXBElement<MisbehaviorFault> createMisbehaviorFault(MisbehaviorFault value) {
        return new JAXBElement<MisbehaviorFault>(_MisbehaviorFault_QNAME, MisbehaviorFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseFundsCallbackResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReleaseFundsCallbackResponse")
    public JAXBElement<ReleaseFundsCallbackResponse> createReleaseFundsCallbackResponse(ReleaseFundsCallbackResponse value) {
        return new JAXBElement<ReleaseFundsCallbackResponse>(_ReleaseFundsCallbackResponse_QNAME, ReleaseFundsCallbackResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogicalFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "LogicalFault")
    public JAXBElement<LogicalFault> createLogicalFault(LogicalFault value) {
        return new JAXBElement<LogicalFault>(_LogicalFault_QNAME, LogicalFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckMsisdnResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "CheckMsisdnResponse")
    public JAXBElement<CheckMsisdnResponse> createCheckMsisdnResponse(CheckMsisdnResponse value) {
        return new JAXBElement<CheckMsisdnResponse>(_CheckMsisdnResponse_QNAME, CheckMsisdnResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "GenericFault")
    public JAXBElement<GenericFault> createGenericFault(GenericFault value) {
        return new JAXBElement<GenericFault>(_GenericFault_QNAME, GenericFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "SystemFault")
    public JAXBElement<SystemFault> createSystemFault(SystemFault value) {
        return new JAXBElement<SystemFault>(_SystemFault_QNAME, SystemFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberCallback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberCallback")
    public JAXBElement<ChargeSubscriberCallback> createChargeSubscriberCallback(ChargeSubscriberCallback value) {
        return new JAXBElement<ChargeSubscriberCallback>(_ChargeSubscriberCallback_QNAME, ChargeSubscriberCallback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberCallbackResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberCallbackResponse")
    public JAXBElement<ChargeSubscriberCallbackResponse> createChargeSubscriberCallbackResponse(ChargeSubscriberCallbackResponse value) {
        return new JAXBElement<ChargeSubscriberCallbackResponse>(_ChargeSubscriberCallbackResponse_QNAME, ChargeSubscriberCallbackResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ServiceFault")
    public JAXBElement<ServiceFault> createServiceFault(ServiceFault value) {
        return new JAXBElement<ServiceFault>(_ServiceFault_QNAME, ServiceFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSubscriberInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "GetSubscriberInfoRequest")
    public JAXBElement<GetSubscriberInfoRequest> createGetSubscriberInfoRequest(GetSubscriberInfoRequest value) {
        return new JAXBElement<GetSubscriberInfoRequest>(_GetSubscriberInfoRequest_QNAME, GetSubscriberInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ConveyResponse")
    public JAXBElement<String> createConveyResponse(String value) {
        return new JAXBElement<String>(_ConveyResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestRefundSubscriberCallback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RequestRefundSubscriberCallback")
    public JAXBElement<RequestRefundSubscriberCallback> createRequestRefundSubscriberCallback(RequestRefundSubscriberCallback value) {
        return new JAXBElement<RequestRefundSubscriberCallback>(_RequestRefundSubscriberCallback_QNAME, RequestRefundSubscriberCallback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "PartnerId")
    public JAXBElement<String> createPartnerId(String value) {
        return new JAXBElement<String>(_PartnerId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSubscriberImsiRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "GetSubscriberImsiRequest")
    public JAXBElement<GetSubscriberImsiRequest> createGetSubscriberImsiRequest(GetSubscriberImsiRequest value) {
        return new JAXBElement<GetSubscriberImsiRequest>(_GetSubscriberImsiRequest_QNAME, GetSubscriberImsiRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberImmediatelyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberImmediatelyRequest")
    public JAXBElement<ChargeSubscriberImmediatelyRequest> createChargeSubscriberImmediatelyRequest(ChargeSubscriberImmediatelyRequest value) {
        return new JAXBElement<ChargeSubscriberImmediatelyRequest>(_ChargeSubscriberImmediatelyRequest_QNAME, ChargeSubscriberImmediatelyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSubscriberInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "GetSubscriberInfoResponse")
    public JAXBElement<GetSubscriberInfoResponse> createGetSubscriberInfoResponse(GetSubscriberInfoResponse value) {
        return new JAXBElement<GetSubscriberInfoResponse>(_GetSubscriberInfoResponse_QNAME, GetSubscriberInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSMSRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "SendSMSRequest")
    public JAXBElement<SendSMSRequest> createSendSMSRequest(SendSMSRequest value) {
        return new JAXBElement<SendSMSRequest>(_SendSMSRequest_QNAME, SendSMSRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ConveySMSResponse")
    public JAXBElement<String> createConveySMSResponse(String value) {
        return new JAXBElement<String>(_ConveySMSResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReserveFundsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReserveFundsResponse")
    public JAXBElement<ReserveFundsResponse> createReserveFundsResponse(ReserveFundsResponse value) {
        return new JAXBElement<ReserveFundsResponse>(_ReserveFundsResponse_QNAME, ReserveFundsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseFundsCallback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReleaseFundsCallback")
    public JAXBElement<ReleaseFundsCallback> createReleaseFundsCallback(ReleaseFundsCallback value) {
        return new JAXBElement<ReleaseFundsCallback>(_ReleaseFundsCallback_QNAME, ReleaseFundsCallback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConveySMSRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ConveySMSRequest")
    public JAXBElement<ConveySMSRequest> createConveySMSRequest(ConveySMSRequest value) {
        return new JAXBElement<ConveySMSRequest>(_ConveySMSRequest_QNAME, ConveySMSRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConveyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ConveyRequest")
    public JAXBElement<ConveyRequest> createConveyRequest(ConveyRequest value) {
        return new JAXBElement<ConveyRequest>(_ConveyRequest_QNAME, ConveyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckMsisdnRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "CheckMsisdnRequest")
    public JAXBElement<CheckMsisdnRequest> createCheckMsisdnRequest(CheckMsisdnRequest value) {
        return new JAXBElement<CheckMsisdnRequest>(_CheckMsisdnRequest_QNAME, CheckMsisdnRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundSubscriberCallback }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RefundSubscriberCallback")
    public JAXBElement<RefundSubscriberCallback> createRefundSubscriberCallback(RefundSubscriberCallback value) {
        return new JAXBElement<RefundSubscriberCallback>(_RefundSubscriberCallback_QNAME, RefundSubscriberCallback.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseFundsMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReleaseFundsMessageResponse")
    public JAXBElement<ReleaseFundsMessageResponse> createReleaseFundsMessageResponse(ReleaseFundsMessageResponse value) {
        return new JAXBElement<ReleaseFundsMessageResponse>(_ReleaseFundsMessageResponse_QNAME, ReleaseFundsMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundSubscriberMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RefundSubscriberMessageResponse")
    public JAXBElement<RefundSubscriberMessageResponse> createRefundSubscriberMessageResponse(RefundSubscriberMessageResponse value) {
        return new JAXBElement<RefundSubscriberMessageResponse>(_RefundSubscriberMessageResponse_QNAME, RefundSubscriberMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestRefundSubscriberMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RequestRefundSubscriberMessage")
    public JAXBElement<RequestRefundSubscriberMessage> createRequestRefundSubscriberMessage(RequestRefundSubscriberMessage value) {
        return new JAXBElement<RequestRefundSubscriberMessage>(_RequestRefundSubscriberMessage_QNAME, RequestRefundSubscriberMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberMessageResponse")
    public JAXBElement<ChargeSubscriberMessageResponse> createChargeSubscriberMessageResponse(ChargeSubscriberMessageResponse value) {
        return new JAXBElement<ChargeSubscriberMessageResponse>(_ChargeSubscriberMessageResponse_QNAME, ChargeSubscriberMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundSubscriberMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RefundSubscriberMessage")
    public JAXBElement<RefundSubscriberMessage> createRefundSubscriberMessage(RefundSubscriberMessage value) {
        return new JAXBElement<RefundSubscriberMessage>(_RefundSubscriberMessage_QNAME, RefundSubscriberMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberImmediatelyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberImmediatelyResponse")
    public JAXBElement<ChargeSubscriberImmediatelyResponse> createChargeSubscriberImmediatelyResponse(ChargeSubscriberImmediatelyResponse value) {
        return new JAXBElement<ChargeSubscriberImmediatelyResponse>(_ChargeSubscriberImmediatelyResponse_QNAME, ChargeSubscriberImmediatelyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReserveFundsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ReserveFundsRequest")
    public JAXBElement<ReserveFundsRequest> createReserveFundsRequest(ReserveFundsRequest value) {
        return new JAXBElement<ReserveFundsRequest>(_ReserveFundsRequest_QNAME, ReserveFundsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefundSubscriberCallbackResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RefundSubscriberCallbackResponse")
    public JAXBElement<RefundSubscriberCallbackResponse> createRefundSubscriberCallbackResponse(RefundSubscriberCallbackResponse value) {
        return new JAXBElement<RefundSubscriberCallbackResponse>(_RefundSubscriberCallbackResponse_QNAME, RefundSubscriberCallbackResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendSMSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "SendSMSResponse")
    public JAXBElement<SendSMSResponse> createSendSMSResponse(SendSMSResponse value) {
        return new JAXBElement<SendSMSResponse>(_SendSMSResponse_QNAME, SendSMSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChargeSubscriberMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "ChargeSubscriberMessage")
    public JAXBElement<ChargeSubscriberMessage> createChargeSubscriberMessage(ChargeSubscriberMessage value) {
        return new JAXBElement<ChargeSubscriberMessage>(_ChargeSubscriberMessage_QNAME, ChargeSubscriberMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestRefundSubscriberCallbackResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "RequestRefundSubscriberCallbackResponse")
    public JAXBElement<RequestRefundSubscriberCallbackResponse> createRequestRefundSubscriberCallbackResponse(RequestRefundSubscriberCallbackResponse value) {
        return new JAXBElement<RequestRefundSubscriberCallbackResponse>(_RequestRefundSubscriberCallbackResponse_QNAME, RequestRefundSubscriberCallbackResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:vimpelcom:carrier-billing-hub:types", name = "PolicyFault")
    public JAXBElement<PolicyFault> createPolicyFault(PolicyFault value) {
        return new JAXBElement<PolicyFault>(_PolicyFault_QNAME, PolicyFault.class, null, value);
    }

}
