//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:vimpelcom:carrier-billing-hub:types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package Subscriber;
