//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refundSubscriberMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="refundSubscriberMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:vimpelcom:carrier-billing-hub:types}billingOperationMessage">
 *       &lt;group ref="{urn:vimpelcom:carrier-billing-hub:types}partialRefundParameters" minOccurs="0"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "refundSubscriberMessage", propOrder = {
    "partialRefundId",
    "refundAmount"
})
public class RefundSubscriberMessage
    extends BillingOperationMessage
{

    @XmlElement(name = "PartialRefundId")
    protected String partialRefundId;
    @XmlElement(name = "RefundAmount")
    protected Long refundAmount;

    /**
     * Gets the value of the partialRefundId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialRefundId() {
        return partialRefundId;
    }

    /**
     * Sets the value of the partialRefundId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialRefundId(String value) {
        this.partialRefundId = value;
    }

    /**
     * Gets the value of the refundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * Sets the value of the refundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRefundAmount(Long value) {
        this.refundAmount = value;
    }

}
