//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestedSubscriberAttribute.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="requestedSubscriberAttribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="is_eligible"/>
 *     &lt;enumeration value="address"/>
 *     &lt;enumeration value="city"/>
 *     &lt;enumeration value="state"/>
 *     &lt;enumeration value="country"/>
 *     &lt;enumeration value="postal_code"/>
 *     &lt;enumeration value="account_type"/>
 *     &lt;enumeration value="limit"/>
 *     &lt;enumeration value="currency"/>
 *     &lt;enumeration value="pii_tos_url"/>
 *     &lt;enumeration value="pii_tos_ver"/>
 *     &lt;enumeration value="dcb_tos_url"/>
 *     &lt;enumeration value="dcb_tos_ver"/>
 *     &lt;enumeration value="services"/>
 *     &lt;enumeration value="BillingAccountNumber"/>
 *     &lt;enumeration value="ContractStartDateTime"/>
 *     &lt;enumeration value="LastLimitErrorDateTime"/>
 *     &lt;enumeration value="Balance"/>
 *     &lt;enumeration value="LastPurchaseDateTime"/>
 *     &lt;enumeration value="AutoBankCardTopup"/>
 *     &lt;enumeration value="MonthlySpendLimit"/>
 *     &lt;enumeration value="MonthlySpendLimitType"/>
 *     &lt;enumeration value="FailedPurchasesNumber"/>
 *     &lt;enumeration value="MSISDN"/>
 *     &lt;enumeration value="PrepaidBalance"/>
 *     &lt;enumeration value="PostpaidTotalPaymentDue"/>
 *     &lt;enumeration value="PostpaidUnbilledPaymentDue"/>
 *     &lt;enumeration value="PostpaidBilledPaymentDue"/>
 *     &lt;enumeration value="PostpaidPaymentDueDate"/>
 *     &lt;enumeration value="ActiveServiceList"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "requestedSubscriberAttribute")
@XmlEnum
public enum RequestedSubscriberAttribute {


    /**
     * Is subscriber eligible for direct carrier billing?
     * 
     */
    @XmlEnumValue("is_eligible")
    IS_ELIGIBLE("is_eligible"),

    /**
     * Subscriber address. May consist of one or several lines (e.g. street address and building details may reside on different lines).
     * 
     */
    @XmlEnumValue("address")
    ADDRESS("address"),

    /**
     * City, town, locality.
     * 
     */
    @XmlEnumValue("city")
    CITY("city"),

    /**
     * State, region, province, regional entity.
     * 
     */
    @XmlEnumValue("state")
    STATE("state"),

    /**
     * ISO 3166-1 country code.
     * 
     */
    @XmlEnumValue("country")
    COUNTRY("country"),

    /**
     * Postal service code.
     * 
     */
    @XmlEnumValue("postal_code")
    POSTAL_CODE("postal_code"),

    /**
     * One of subscriber account types: “prepaid”, “postpaid”, “enterprise”.
     * 
     */
    @XmlEnumValue("account_type")
    ACCOUNT_TYPE("account_type"),

    /**
     * The maximum limit of a single transaction allowed by the OpCo for this subscriber. Must be an integer greater than 0.
     * 
     */
    @XmlEnumValue("limit")
    LIMIT("limit"),

    /**
     * ISO 4217 code of the accepted currency for this account.
     * 
     */
    @XmlEnumValue("currency")
    CURRENCY("currency"),

    /**
     * URL which points to the OpCo's billing Terms Of Service, to be viewed by the subscriber.
     * 
     */
    @XmlEnumValue("pii_tos_url")
    PII_TOS_URL("pii_tos_url"),

    /**
     * Latest version of the TOS that should be accepted by the user prior to performing purchases.
     * 
     */
    @XmlEnumValue("pii_tos_ver")
    PII_TOS_VER("pii_tos_ver"),

    /**
     * URL which points to the OpCo's billing Terms Of Service, to be viewed by the subscriber.
     * 
     */
    @XmlEnumValue("dcb_tos_url")
    DCB_TOS_URL("dcb_tos_url"),

    /**
     * Latest version of the TOS that should be accepted by the user prior to performing purchases.
     * 
     */
    @XmlEnumValue("dcb_tos_ver")
    DCB_TOS_VER("dcb_tos_ver"),

    /**
     * List of requesting partner services for which Subscriber is eligible. Comma separated list of alphanumeric service identifiers.
     * 
     */
    @XmlEnumValue("services")
    SERVICES("services"),

    /**
     * Subscriber’s billing account number.
     * 
     */
    @XmlEnumValue("BillingAccountNumber")
    BILLING_ACCOUNT_NUMBER("BillingAccountNumber"),

    /**
     * Date and time of Subscriber contract creation.
     * 
     */
    @XmlEnumValue("ContractStartDateTime")
    CONTRACT_START_DATE_TIME("ContractStartDateTime"),

    /**
     * Date and time of last Subscriber attempt to purchase OTT Partner services which was declined because spending threshold was reached.
     * 
     */
    @XmlEnumValue("LastLimitErrorDateTime")
    LAST_LIMIT_ERROR_DATE_TIME("LastLimitErrorDateTime"),

    /**
     * Subscriber balance available for OTT Partner services purchases.
     * 
     */
    @XmlEnumValue("Balance")
    BALANCE("Balance"),

    /**
     * Date and time of last purchase of OTT Partner content by the Subscriber.
     * 
     */
    @XmlEnumValue("LastPurchaseDateTime")
    LAST_PURCHASE_DATE_TIME("LastPurchaseDateTime"),

    /**
     * Boolean value indicating that Subscriber has automatic topup of his main balance from bank card set up and active.
     * 
     */
    @XmlEnumValue("AutoBankCardTopup")
    AUTO_BANK_CARD_TOPUP("AutoBankCardTopup"),

    /**
     * Decimal value representing Subscriber monthly spend limit for OTT Partner services in Subscriber’s account currency.
     * 
     */
    @XmlEnumValue("MonthlySpendLimit")
    MONTHLY_SPEND_LIMIT("MonthlySpendLimit"),

    /**
     * String value describing how monthly spending limit is calculated
     * 
     */
    @XmlEnumValue("MonthlySpendLimitType")
    MONTHLY_SPEND_LIMIT_TYPE("MonthlySpendLimitType"),

    /**
     * Number of failed OTT Partner purchase transactions for the particular Subscriber for the last 30 days.
     * 
     */
    @XmlEnumValue("FailedPurchasesNumber")
    FAILED_PURCHASES_NUMBER("FailedPurchasesNumber"),

    /**
     * Subscriber’s MSISDN.
     * 
     */
    MSISDN("MSISDN"),

    /**
     * Prepaid subscriber effective balance.
     * 
     */
    @XmlEnumValue("PrepaidBalance")
    PREPAID_BALANCE("PrepaidBalance"),

    /**
     * Total amount of the subscriber account credit.
     * 
     */
    @XmlEnumValue("PostpaidTotalPaymentDue")
    POSTPAID_TOTAL_PAYMENT_DUE("PostpaidTotalPaymentDue"),

    /**
     * Unbilled amount of the subscriber account credit.
     * 
     */
    @XmlEnumValue("PostpaidUnbilledPaymentDue")
    POSTPAID_UNBILLED_PAYMENT_DUE("PostpaidUnbilledPaymentDue"),

    /**
     * Billed amount of the subscriber account credit.
     * 
     */
    @XmlEnumValue("PostpaidBilledPaymentDue")
    POSTPAID_BILLED_PAYMENT_DUE("PostpaidBilledPaymentDue"),

    /**
     * A date payment due to be paid by a subscriber.
     * 
     */
    @XmlEnumValue("PostpaidPaymentDueDate")
    POSTPAID_PAYMENT_DUE_DATE("PostpaidPaymentDueDate"),

    /**
     * Effective subscriber services list.
     * 
     */
    @XmlEnumValue("ActiveServiceList")
    ACTIVE_SERVICE_LIST("ActiveServiceList");
    private final String value;

    RequestedSubscriberAttribute(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestedSubscriberAttribute fromValue(String v) {
        for (RequestedSubscriberAttribute c: RequestedSubscriberAttribute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
