//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 04:18:49 PM PKT 
//


package Subscriber;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for systemFaultCause.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="systemFaultCause">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="SYSTEM_DOWN"/>
 *     &lt;enumeration value="SYSTEM_BUSY"/>
 *     &lt;enumeration value="GENERAL_DECLINE"/>
 *     &lt;enumeration value="INDEFINITE_RESULT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "systemFaultCause")
@XmlEnum
public enum SystemFaultCause {


    /**
     * 
     *                         Some OpCo system participating in the requested operation is down.
     *                         Means that processing of requested transaction was unsuccessful due to temporary unavailability 
     *                         of some OpCo systems, but the same request may be repeated later if needed and has a chance 
     *                         to be processed properly upon involved systems recovery.
     *                     
     * 
     */
    SYSTEM_DOWN,

    /**
     * 
     *                         Some OpCo system participating in the requested operation declined transaction processing due to high load. 
     *                         Means that processing of requested transaction was unsuccessful because it exceeded available 
     *                         capacity of some OpCo systems, but the same request may be repeated later if needed and has 
     *                         a chance to be processed properly upon involved systems processing capacity becomes available.
     *                     
     * 
     */
    SYSTEM_BUSY,

    /**
     * 
     *                         Transaction is declined by OpCo internal systems due to reasons, which could not be described by other Causes. 
     *                         Means that processing of requested transaction was unsuccessful due to unforeseen reasons 
     *                         such as data inconsistency or software errors in one of OpCo systems. Automatic reprocessing 
     *                         of the same request is not possible until cause of the fault is eliminated.
     *                     
     * 
     */
    GENERAL_DECLINE,

    /**
     * 
     *                         Definite result of transaction processing is not known. 
     *                         This may happen due to processing of the request did not end within agreed time interval or 
     *                         result of processing was not delivered due to network level problems. In this situation calling 
     *                         party MUST repeat request to retrieve result and make transaction state consistent between 
     *                         all the involved systems.
     *                     
     * 
     */
    INDEFINITE_RESULT;

    public String value() {
        return name();
    }

    public static SystemFaultCause fromValue(String v) {
        return valueOf(v);
    }

}
